In [1]:
import numpy as np
import pandas as pd

In [2]:
airports = pd.read_csv('airports.csv')

In [3]:
airports.head()

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
0,6523,00A,heliport,Total Rf Heliport,40.070801,-74.933601,11.0,NaN,US,US-PA,Bensalem,no,00A,NaN,00A,NaN,NaN,NaN
1,323361,00AA,small_airport,Aero B Ranch Airport,38.704022,-101.473911,3435.0,NaN,US,US-KS,Leoti,no,00AA,NaN,00AA,NaN,NaN,NaN
2,6524,00AK,small_airport,Lowell Field,59.947733,-151.692524,450.0,NaN,US,US-AK,Anchor Point,no,00AK,NaN,00AK,NaN,NaN,NaN
3,6525,00AL,small_airport,Epps Airpark,34.864799,-86.770302,820.0,NaN,US,US-AL,Harvest,no,00AL,NaN,00AL,NaN,NaN,NaN
4,506791,00AN,small_airport,Katmai Lodge Airport,59.093287,-156.456699,80.0,NaN,US,US-AK,King Salmon,no,00AN,NaN,00AN,NaN,NaN,NaN

In [6]:
df_euro = airports[airports['continent'] == 'EU']
df_euro2 = df_euro[df_euro['iso_country'] != 'RU']

In [8]:
df_euro2['iso_country'].unique()

array(['GB', 'AD', 'AL', 'XK', 'AT', 'BA', 'BE', 'BG', 'IS', 'BY', 'UA',
       'CH', 'CZ', 'SK', 'DE', 'DK', 'EE', 'FI', 'GG', 'JE', 'IM', 'NL',
       'IE', 'FO', 'LU', 'NO', 'PL', 'ES', 'PT', 'SE', 'LV', 'LT', 'FR',
       'GR', 'HR', 'HU', 'IT', 'KZ', 'LI', 'SM', 'SI', 'MT', 'MC', 'RO',
       'TR', 'MD', 'MK', 'GI', 'RS', 'ME', 'GE', 'VA'], dtype=object)

In [10]:
df_euro3 = df_euro2[df_euro2['iso_country'] != 'UA']

In [11]:
df_euro3.head()

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
10933,307979,ABE,closed,RAF Calveley,53.113333,-2.603889,NaN,EU,GB,GB-ENG,Cheshire,no,NaN,NaN,NaN,NaN,https://en.wikipedia.org/wiki/RAF_Calveley,NaN
10934,302247,ABL,closed,RNAS/RAF Calshot,50.819913,-1.306772,NaN,EU,GB,GB-ENG,Hampshire,no,NaN,NaN,NaN,NaN,https://en.wikipedia.org/wiki/RAF_Calshot,NaN
10939,318235,AD-0001,heliport,Terra Guindaldes Heliport,42.546257,1.519160,NaN,EU,AD,AD-04,La Massana,no,NaN,NaN,NaN,NaN,NaN,NaN
10940,338490,AD-0002,closed,Arinsal (Coll de la Botella) Heliport,42.544983,1.452258,NaN,EU,AD,AD-04,La Massana,no,NaN,NaN,NaN,NaN,NaN,NaN
10941,41841,AD-ALV,heliport,Andorra la Vella (Our Lady of Meritxell Hospit...,42.511228,1.533651,3450.0,EU,AD,AD-08,Escaldes-Engordany,no,NaN,NaN,NaN,NaN,http://pl.wikipedia.org/wiki/Heliport_Andorra_...,NaN